<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function dspace_help($path, $arg) {
  switch ($path) {
    case "admin/help#dspace":
      return '<p>' . t("Import DSpace items into Drupal as Biblio nodes. Requires the the <a href='https://wiki.duraspace.org/display/DSPACE/REST+API'>DSpace REST API plugin</a>") . '</p>';
      break;
  }
}

/**
 * Implementation of hook_feeds_plugins().
 */
function dspace_feeds_plugins() {
  $info = array();
  $info['FeedsDSpaceParser'] = array(
    'name' => 'DSpace Feeds parser',
    'description' => 'Parses DSpace XML feed.',
    'handler' => array(
      'parent' => 'FeedsParser', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'FeedsDSpaceParser',
      'file' => 'FeedsDSpaceParser.inc',
      'path' => drupal_get_path('module', 'dspace'),
    ),
  );
  return $info;
}

/**
 * Implementation of hook_enable().
 */
function dspace_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}